import { runUnifiedVisionAnalysis } from './aiVision.service';
import { findIndiaFood, IndiaFoodCatalogItem } from '../db/indiaFoodCatalog';

export interface NutritionEstimate { calories:number; protein:number; carbs:number; fat:number; fiber:number; sugar:number; sodium:number; saturatedFat:number; }
export interface IdentifiedFoodItem { name:string; estimatedPortion:string; confidence:number; isEstimated:boolean; dataSource:string; nutrition:NutritionEstimate; }
export interface MealIntelligenceResult { detectedDishName:string; items:IdentifiedFoodItem[]; totalNutrition:NutritionEstimate; confidence:{itemsRecognition:number;portionVolume:number;totalNutrition:number;overall:number}; isEstimated:boolean; primaryDataSource:string; estimationDisclaimer:string; likelyIngredients:string[]; healthSummary:string; uncertaintyWarnings?:string[]; }
export const MANDATORY_MEAL_DISCLAIMER='All caloric, portion, and nutrient values are visual AI estimations based on computer vision volume heuristics and food database references. They are not exact laboratory measurements.';
const n=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?Math.max(0,v):0; const c=(v:unknown)=>Math.max(0,Math.min(1,n(v)));
const grams=(value:string)=>{const m=value.match(/(?:~|about|approx\.?|around)?\s*(\d+(?:\.\d+)?)\s*(?:g|grams?)\b/i);return m?Number(m[1]):null;};
const normalizeItem=(item:any):IdentifiedFoodItem=>({name:typeof item?.name==='string'&&item.name.trim()?item.name.trim():'Unknown food item',estimatedPortion:typeof item?.estimatedPortion==='string'&&item.estimatedPortion.trim()?item.estimatedPortion.trim():'Portion not reliably estimated',confidence:c(item?.confidence),isEstimated:true,dataSource:typeof item?.dataSource==='string'&&item.dataSource.trim()?item.dataSource.trim():'AI Vision Estimate',nutrition:{calories:n(item?.nutrition?.calories),protein:n(item?.nutrition?.protein),carbs:n(item?.nutrition?.carbs),fat:n(item?.nutrition?.fat),fiber:n(item?.nutrition?.fiber),sugar:n(item?.nutrition?.sugar),sodium:n(item?.nutrition?.sodium),saturatedFat:n(item?.nutrition?.saturatedFat)}});
const catalogNutrition=(item:IndiaFoodCatalogItem,portionText:string):NutritionEstimate=>{const g=grams(portionText);const factor=g&&g>0?g/item.portionGrams:1;return {calories:Math.round(item.calories*factor),protein:Math.round(item.protein*factor*10)/10,carbs:Math.round(item.carbs*factor*10)/10,fat:Math.round(item.fat*factor*10)/10,fiber:Math.round(item.fiber*factor*10)/10,sugar:Math.round(item.sugar*factor*10)/10,sodium:Math.round(item.sodium*factor),saturatedFat:Math.round(item.saturatedFat*factor*10)/10};};
const validateNutrition=(item:IdentifiedFoodItem)=>{const x=item.nutrition,w:string[]=[];const kcal=4*x.protein+4*x.carbs+9*x.fat+2*x.fiber;if(x.calories&&kcal&&Math.abs(x.calories-kcal)/Math.max(x.calories,kcal)>0.45)w.push(`${item.name}: calories are inconsistent with reported macros`);if(x.sugar>x.carbs&&x.carbs>0)w.push(`${item.name}: sugar exceeds carbohydrates`);if(x.saturatedFat>x.fat&&x.fat>0)w.push(`${item.name}: saturated fat exceeds total fat`);return w;};
const calculateTotals=(items:IdentifiedFoodItem[]):NutritionEstimate=>items.reduce((a,i)=>({calories:a.calories+i.nutrition.calories,protein:a.protein+i.nutrition.protein,carbs:a.carbs+i.nutrition.carbs,fat:a.fat+i.nutrition.fat,fiber:a.fiber+i.nutrition.fiber,sugar:a.sugar+i.nutrition.sugar,sodium:a.sodium+i.nutrition.sodium,saturatedFat:a.saturatedFat+i.nutrition.saturatedFat}),{calories:0,protein:0,carbs:0,fat:0,fiber:0,sugar:0,sodium:0,saturatedFat:0});

export const runMealIntelligencePipeline=async(params:{imageBase64:string;mimeType?:string;customDishName?:string;foodCategory?:string}):Promise<MealIntelligenceResult>=>{
 const {imageBase64,mimeType,customDishName,foodCategory}=params;
 const prompt=`You are a food computer-vision engine. Analyze ONLY the supplied image. Detect every visually distinct edible food item. Do not invent foods or hidden ingredients. Context: ${foodCategory==='HOME_FOOD'?'homemade home-cooked food':foodCategory==='OUTSIDE_PACKAGED'?'packaged/store-bought food':'restaurant/dining dish'}. ${customDishName?`User hint (not proof): ${customDishName}`:''}
Return one item per distinct visible food component, with a concrete approximate portion. Never claim exact weight from a photo. Nutrition should be an estimate for that portion. Return STRICT JSON ONLY: {"detectedDishName":"...","items":[{"name":"...","estimatedPortion":"~150 g","confidence":0.8,"isEstimated":true,"dataSource":"AI Vision Estimate","nutrition":{"calories":250,"protein":10,"carbs":30,"fat":8,"fiber":4,"sugar":5,"sodium":300,"saturatedFat":2}}],"confidence":{"itemsRecognition":0.85,"portionVolume":0.7,"totalNutrition":0.8,"overall":0.78},"isEstimated":true,"primaryDataSource":"AI Vision Estimate","estimationDisclaimer":"${MANDATORY_MEAL_DISCLAIMER}","likelyIngredients":[],"healthSummary":"...","uncertaintyWarnings":[]}`;
 const result=await runUnifiedVisionAnalysis({prompt,imageBase64,mimeType,scanType:'MEAL'});if(!result)throw new Error('Food image analysis failed. Please try again.');const rawItems=Array.isArray(result.items)?result.items:[];if(!rawItems.length)throw new Error('No distinct food items could be identified reliably. Please use a clearer meal photo.');
 const warnings=new Set<string>(Array.isArray(result.uncertaintyWarnings)?result.uncertaintyWarnings.filter((x:any)=>typeof x==='string'):[]);
 const items=rawItems.slice(0,12).map(normalizeItem).map((aiItem)=>{const catalog=findIndiaFood(aiItem.name);if(!catalog)return aiItem;const portionGrams=grams(aiItem.estimatedPortion);const nutrition=catalogNutrition(catalog,aiItem.estimatedPortion);if(!portionGrams)warnings.add(`${aiItem.name}: using the catalog reference portion because the photo portion could not be converted to grams.`);return {...aiItem,name:catalog.name,nutrition,dataSource:`India Food Catalog + visual portion estimate (${catalog.portionLabel})`,confidence:Math.min(1,Math.max(aiItem.confidence,0.82)),isEstimated:true};});
 items.forEach(i=>validateNutrition(i).forEach(w=>warnings.add(w)));const totalNutrition=calculateTotals(items);const recognition=c(result.confidence?.itemsRecognition),portion=c(result.confidence?.portionVolume),nutritionConfidence=c(result.confidence?.totalNutrition);const overall=Math.min(c(result.confidence?.overall||((recognition+portion+nutritionConfidence)/3)),recognition||1,portion||1);if(items.length>1)warnings.add(`Detected ${items.length} distinct food items; nutrition is calculated separately and then summed.`);if(portion<0.7)warnings.add('Portion size is uncertain because a normal photo cannot provide an exact weight.');
 return {detectedDishName:typeof result.detectedDishName==='string'&&result.detectedDishName.trim()?result.detectedDishName.trim():items[0].name,items,totalNutrition,confidence:{itemsRecognition:recognition,portionVolume:portion,totalNutrition:nutritionConfidence,overall:Math.round(overall*100)/100},isEstimated:true,primaryDataSource:items.some(i=>i.dataSource.startsWith('India Food Catalog'))?'India Food Catalog + AI Vision':'AI Vision Estimate',estimationDisclaimer:MANDATORY_MEAL_DISCLAIMER,likelyIngredients:Array.isArray(result.likelyIngredients)?result.likelyIngredients.filter((x:any)=>typeof x==='string').slice(0,30):[],healthSummary:typeof result.healthSummary==='string'?result.healthSummary:'Nutrition and portion values are estimates; verify important details where possible.',uncertaintyWarnings:[...warnings]};
};
export const analyzeFoodFromImage=(_imageBase64:string,_customDishName?:string,_foodCategory?:string):MealIntelligenceResult=>{throw new Error('Food image analysis failed. Please try again.');};
