import { fetchBarcodeData, BarcodeProductResult } from './barcode.service';
import { runUnifiedVisionAnalysis } from './aiVision.service';
import { selectReliableField, validateNutrition, clamp01, EvidenceSource } from './dataConfidence.service';

export type DataSourceType = EvidenceSource;
export interface FieldConfidence { productName:number; ingredients:number; nutrition:number; allergens:number; overall:number; }
export interface DataSourcesMap { productName:DataSourceType; brandName:DataSourceType; ingredients:DataSourceType; nutrition:DataSourceType; allergens:DataSourceType; additives:DataSourceType; }
export interface PackagedIntelligenceResult { productName:string; brandName?:string; barcode?:string; nutritionScore?:string; nutrition:{calories:number;proteins:number;carbs:number;fats:number;sugar:number;sodium:number;saturatedFat:number}; truthRating:{score:number;maxScore:number;ratingLabel:string;ratingColor:string}; novaGroup:{level:1|2|3|4;label:string;description:string;badgeColor:string}; trafficLight:{overallStatus:'GREEN'|'YELLOW'|'RED';sugarStatus:'GREEN'|'YELLOW'|'RED';sodiumStatus:'GREEN'|'YELLOW'|'RED';fatStatus:'GREEN'|'YELLOW'|'RED'}; healthierSwaps:Array<{name:string;brand:string;calories:number;rating:number;reason:string}>; hiddenIngredientsAlert:{hiddenSugars:string[];cheapOils:string[]}; ingredients:string[];detectedAllergens:string[]; additives:Array<{code:string;name:string;safety:'Safe'|'Use in Moderation'|'Avoid';explanation:string}>; healthHighlights:Array<{type:'warning'|'info'|'good';label:string;description:string}>;summary:string;rawOcrText:string;confidence:FieldConfidence;sources:DataSourcesMap;missingFields:string[];uncertaintyWarnings:string[];isValidated:boolean; }
const emptyNutrition=()=>({calories:0,proteins:0,carbs:0,fats:0,sugar:0,sodium:0,saturatedFat:0});
const identityTokens=(v?:string)=> (v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(t=>t.length>=3&&!['the','and','with','for'].includes(t));
const identitySimilarity=(a?:string,b?:string)=>{const x=new Set(identityTokens(a)),y=new Set(identityTokens(b));if(!x.size||!y.size)return 0;let n=0;for(const t of x)if(y.has(t))n++;return n/Math.max(1,Math.min(x.size,y.size));};

export const runPackagedIntelligencePipeline=async(params:{barcode?:string;imageBase64?:string;mimeType?:string;customItemName?:string;foodCategory?:string}):Promise<PackagedIntelligenceResult>=>{const {barcode,imageBase64,mimeType,customItemName,foodCategory}=params;let dbData:BarcodeProductResult|null=null;if(barcode)dbData=await fetchBarcodeData(barcode);let ocrResult:Partial<PackagedIntelligenceResult>|null=null;if(imageBase64){const prompt=`Analyze this packaged food image. Identify the exact visible brand and product variant only when supported by the image. OCR the nutrition panel and ingredient list exactly; do not invent unreadable values. If text is unreadable, return empty arrays/zero values for unavailable fields and add uncertainty warnings. Do not use knowledge of visually similar products. Return strict JSON only with productName, brandName, nutrition (calories, proteins, carbs, fats, sugar, sodium, saturatedFat), ingredients, detectedAllergens, additives, summary, rawOcrText, confidence (productName, ingredients, nutrition, allergens, overall), missingFields, uncertaintyWarnings.`;ocrResult=await runUnifiedVisionAnalysis({prompt,imageBase64,mimeType,scanType:'PACKAGED'});if(!ocrResult||!ocrResult.productName)throw new Error('Food image analysis failed. Please try again.');}if(!dbData&&!ocrResult&&!barcode&&!customItemName)throw new Error('Food image analysis failed. Please try again.');return mergeAndNormalizePackagedData({barcode,dbData,ocrResult,customItemName,foodCategory});};

const mergeAndNormalizePackagedData=(input:{barcode?:string;dbData:BarcodeProductResult|null;ocrResult:Partial<PackagedIntelligenceResult>|null;customItemName?:string;foodCategory?:string}):PackagedIntelligenceResult=>{const {barcode,dbData,ocrResult,customItemName}=input;const missingFields=new Set<string>();const uncertaintyWarnings=new Set<string>();const ocrConfidence=ocrResult?.confidence||{};
 const rawBarcodeMatch=Boolean(dbData&&barcode&&dbData.barcode===barcode);const productSimilarity=rawBarcodeMatch&&ocrResult?.productName?identitySimilarity(dbData?.productName,ocrResult.productName):0;const brandSimilarity=rawBarcodeMatch&&ocrResult?.brandName?identitySimilarity(dbData?.brandName,ocrResult.brandName):0;const identityConflict=Boolean(rawBarcodeMatch&&ocrResult?.productName&&(ocrConfidence.productName??0)>=0.75&&productSimilarity<0.35&&(!ocrResult.brandName||brandSimilarity<0.35));const hasBarcodeEvidence=rawBarcodeMatch&&!identityConflict;if(identityConflict){uncertaintyWarnings.add('Barcode data conflicts with the visible package identity. Barcode database fields were excluded to avoid reporting data for the wrong product.');missingFields.add('barcodeIdentityVerification');}
 const nameEvidence=selectReliableField<string>([...(customItemName?[{value:customItemName.trim(),source:'AI_ESTIMATE' as EvidenceSource,confidence:0.55}]:[]),...(hasBarcodeEvidence&&dbData?.productName?[{value:dbData.productName,source:'BARCODE_DATABASE' as EvidenceSource,confidence:0.99}]:[]),...(ocrResult?.productName?[{value:ocrResult.productName,source:'PACKAGE_OCR' as EvidenceSource,confidence:clamp01(ocrConfidence.productName??0)}]:[])]);const productName=nameEvidence.value;if(!productName)throw new Error('Unable to identify this packaged product with sufficient evidence.');
 const brandEvidence=selectReliableField<string>([...(hasBarcodeEvidence&&dbData?.brandName?[{value:dbData.brandName,source:'BARCODE_DATABASE' as EvidenceSource,confidence:0.99}]:[]),...(ocrResult?.brandName?[{value:ocrResult.brandName,source:'PACKAGE_OCR' as EvidenceSource,confidence:clamp01(ocrConfidence.productName??0)}]:[])]);const brandName=brandEvidence.value||'Unknown Brand';
 const fields=['calories','proteins','carbs','fats','sugar','sodium','saturatedFat'] as const;const nutrition=emptyNutrition();const nutritionSources:Record<string,DataSourceType>={};let nutritionConfidence=0;for(const field of fields){const evidence=selectReliableField<number>([...(hasBarcodeEvidence&&typeof dbData?.[field]==='number'?[{value:dbData[field] as number,source:'BARCODE_DATABASE' as EvidenceSource,confidence:0.99}]:[]),...(typeof ocrResult?.nutrition?.[field]==='number'&&(ocrResult.nutrition[field] as number)>0?[{value:ocrResult.nutrition[field] as number,source:'PACKAGE_OCR' as EvidenceSource,confidence:clamp01(ocrConfidence.nutrition??0)}]:[])]);if(evidence.value===null){missingFields.add(`nutrition.${field}`);continue;}nutrition[field]=Math.max(0,evidence.value);nutritionSources[field]=evidence.source||'AI_ESTIMATE';nutritionConfidence+=evidence.confidence;}nutritionConfidence/=fields.length;validateNutrition(nutrition).forEach(f=>missingFields.add(`nutrition.${f}`));
 const ingredientsEvidence=selectReliableField<string[]>([...(hasBarcodeEvidence&&dbData?.ingredientsList?.length?[{value:dbData.ingredientsList,source:'BARCODE_DATABASE' as EvidenceSource,confidence:0.99}]:[]),...(ocrResult?.ingredients?.length?[{value:ocrResult.ingredients,source:'PACKAGE_OCR' as EvidenceSource,confidence:clamp01(ocrConfidence.ingredients??0)}]:[])]);const ingredients=ingredientsEvidence.value||[];if(!ingredients.length)missingFields.add('ingredients');
 const allergenEvidence=selectReliableField<string[]>([...(hasBarcodeEvidence&&dbData?.detectedAllergens?.length?[{value:dbData.detectedAllergens,source:'BARCODE_DATABASE' as EvidenceSource,confidence:0.99}]:[]),...(ocrResult?.detectedAllergens?.length?[{value:ocrResult.detectedAllergens,source:'PACKAGE_OCR' as EvidenceSource,confidence:clamp01(ocrConfidence.allergens??0)}]:[])]);const detectedAllergens=allergenEvidence.value||[];if(!detectedAllergens.length)uncertaintyWarnings.add('Allergen information was not verified from a reliable product source. Check the package label before consuming.');
 const additiveEvidence=hasBarcodeEvidence&&dbData?.additives?.length?dbData.additives:(ocrResult?.additives||[]);const additives=additiveEvidence.map(a=>({code:a.code||'Unknown',name:a.name||a.code||'Unknown additive',safety:(a.safety==='Safe'||a.safety==='Avoid')?a.safety:'Use in Moderation' as const,explanation:a.explanation||'Additive information should be verified against the package label.'}));if(!additives.length)uncertaintyWarnings.add('No additives were reliably detected.');
 const rawOcrText=ocrResult?.rawOcrText||dbData?.ingredientsText||'';if(!rawOcrText)missingFields.add('rawOcrText');const sugarStatus=nutrition.sugar>20?'RED':nutrition.sugar>8?'YELLOW':'GREEN';const sodiumStatus=nutrition.sodium>600?'RED':nutrition.sodium>250?'YELLOW':'GREEN';const fatStatus=nutrition.saturatedFat>8?'RED':nutrition.saturatedFat>3?'YELLOW':'GREEN';const overallStatus=[sugarStatus,sodiumStatus,fatStatus].includes('RED')?'RED':[sugarStatus,sodiumStatus,fatStatus].includes('YELLOW')?'YELLOW':'GREEN';
 const novaLevel:1|2|3|4=/syrup|hydrogenated|emulsifier|flavou?r|sweetener|maltodextrin/i.test(ingredients.join(' '))?4:(ingredients.length>5?3:2);const novaGroup={level:novaLevel,label:`NOVA ${novaLevel}: ${novaLevel===4?'Ultra-Processed Food':novaLevel===3?'Processed Food':'Minimally Processed / Processed Ingredient'}`,description:novaLevel===4?'Ingredients suggest an industrially formulated product.':'Processing level is estimated from the available ingredient evidence.',badgeColor:novaLevel===4?'bg-rose-500 text-white':'bg-emerald-600 text-white'};const scoreBase=overallStatus==='RED'?2:overallStatus==='YELLOW'?3:4;const rawTruthScore=Math.max(0,Math.min(5,scoreBase+Math.min(1,nutrition.proteins/20)-(novaLevel===4?0.5:0)));const truthRating={score:Math.round(rawTruthScore*10)/10,maxScore:5,ratingLabel:rawTruthScore>=4?'Health Choice':rawTruthScore>=2.5?'Moderate Choice':'Needs Caution',ratingColor:rawTruthScore>=4?'text-emerald-700 bg-emerald-50 border-emerald-300':rawTruthScore>=2.5?'text-amber-700 bg-amber-50 border-amber-300':'text-rose-700 bg-rose-50 border-rose-300'};
 const hiddenSugars=ingredients.filter(i=>/invert sugar|fructose|maltodextrin|dextrose|glucose syrup/i.test(i));const cheapOils=ingredients.filter(i=>/palm|hydrogenated|palmolein/i.test(i));const healthierSwaps=[];const overallConfidence=Math.min(1,(nameEvidence.confidence+nutritionConfidence+(ingredientsEvidence.confidence||0)+(allergenEvidence.confidence||0))/4);if(overallConfidence<0.75)uncertaintyWarnings.add('Some product fields are estimated or incomplete. Verify important details on the physical package.');if(!hasBarcodeEvidence&&ocrResult&&!identityConflict)uncertaintyWarnings.add('This scan was not matched to a verified barcode record; product identity comes from package evidence.');
 return {productName,brandName,barcode,nutritionScore:hasBarcodeEvidence?dbData?.nutritionScore:ocrResult?.nutritionScore,nutrition,truthRating,novaGroup,trafficLight:{overallStatus,sugarStatus,sodiumStatus,fatStatus},healthierSwaps,hiddenIngredientsAlert:{hiddenSugars,cheapOils},ingredients,detectedAllergens,additives,healthHighlights:[{type:sugarStatus==='RED'?'warning':'info',label:sugarStatus==='RED'?'High Sugar':'Sugar Level',description:`${nutrition.sugar}g sugar per 100g/available serving basis.`},{type:novaLevel===4?'warning':'info',label:novaGroup.label,description:novaGroup.description}],summary:identityConflict?`${productName} by ${brandName} analyzed from package evidence. The supplied barcode record conflicted with the visible product, so database fields were excluded.`:`${productName} by ${brandName} analyzed using available package and/or barcode evidence. Verify warnings and allergens against the physical label.`,rawOcrText,confidence:{productName:Math.round(nameEvidence.confidence*100)/100,ingredients:Math.round((ingredientsEvidence.confidence||0)*100)/100,nutrition:Math.round(nutritionConfidence*100)/100,allergens:Math.round((allergenEvidence.confidence||0)*100)/100,overall:Math.round(overallConfidence*100)/100},sources:{productName:nameEvidence.source||'AI_ESTIMATE',brandName:brandEvidence.source||'AI_ESTIMATE',ingredients:ingredientsEvidence.source||'AI_ESTIMATE',nutrition:(Object.values(nutritionSources)[0]||'AI_ESTIMATE') as DataSourceType,allergens:allergenEvidence.source||'AI_ESTIMATE',additives:hasBarcodeEvidence&&dbData?.additives?.length?'BARCODE_DATABASE':ocrResult?.additives?.length?'PACKAGE_OCR':'AI_ESTIMATE'},missingFields:[...missingFields],uncertaintyWarnings:[...uncertaintyWarnings],isValidated:Boolean(hasBarcodeEvidence||(nameEvidence.source==='PACKAGE_OCR'&&nameEvidence.confidence>=0.9&&ingredients.length>0&&nutritionConfidence>=0.8))};};
