import { IndiaFoodCatalogItem } from './indiaFoodCatalog';

/** Additional common Indian-food reference portions. Estimates are for product/reference matching, not laboratory measurements. */
export const INDIA_FOOD_CATALOG_EXTENDED: IndiaFoodCatalogItem[] = [
{name:'Misal Pav',aliases:['misal pav','misal','misalpaav'],portionGrams:300,portionLabel:'1 plate (~300g)',portionUnitCount:1,calories:420,protein:16,carbs:58,fat:14,fiber:10,sugar:7,sodium:900,saturatedFat:3,ingredients:['sprouted legumes','spicy gravy','onion','farsan','pav','oil']},
{name:'Pav Bhaji',aliases:['pav bhaji','pavbhaji'],portionGrams:350,portionLabel:'1 plate (~350g)',portionUnitCount:1,calories:500,protein:12,carbs:72,fat:18,fiber:10,sugar:9,sodium:1000,saturatedFat:7,ingredients:['mixed vegetables','pav','butter','tomato','spices']},
{name:'Vada Pav',aliases:['vada pav','wadapav','batata vada pav'],portionGrams:180,portionLabel:'1 piece (~180g)',portionUnitCount:1,calories:290,protein:7,carbs:43,fat:10,fiber:5,sugar:4,sodium:600,saturatedFat:2,ingredients:['potato','gram flour','pav','chutney','oil']},
{name:'Medu Vada',aliases:['medu vada','medhu vada','urad vada'],portionGrams:100,portionLabel:'2 medium vadas (~100g)',portionUnitCount:2,calories:250,protein:8,carbs:28,fat:12,fiber:4,sugar:1,sodium:280,saturatedFat:2,ingredients:['urad dal','spices','oil']},
{name:'Pav',aliases:['pav','bread roll','ladi pav'],portionGrams:50,portionLabel:'1 pav (~50g)',portionUnitCount:1,calories:135,protein:4,carbs:25,fat:2,fiber:1,sugar:3,sodium:230,saturatedFat:0.4,ingredients:['wheat flour','yeast','water','salt']},
{name:'Bhindi Masala',aliases:['bhindi masala','okra masala','ladyfinger masala'],portionGrams:180,portionLabel:'1 bowl (~180g)',portionUnitCount:1,calories:170,protein:4,carbs:16,fat:10,fiber:7,sugar:5,sodium:330,saturatedFat:1.2,ingredients:['okra','onion','tomato','spices','oil']},
{name:'Aloo Gobi',aliases:['aloo gobi','aloo gobhi','potato cauliflower'],portionGrams:180,portionLabel:'1 bowl (~180g)',portionUnitCount:1,calories:180,protein:5,carbs:24,fat:8,fiber:6,sugar:5,sodium:330,saturatedFat:1,ingredients:['potato','cauliflower','spices','oil']},
{name:'Baingan Bharta',aliases:['baingan bharta','baingan bharta','eggplant bharta'],portionGrams:180,portionLabel:'1 bowl (~180g)',portionUnitCount:1,calories:150,protein:4,carbs:18,fat:7,fiber:7,sugar:7,sodium:320,saturatedFat:1,ingredients:['eggplant','tomato','onion','spices','oil']},
{name:'Jeera Aloo',aliases:['jeera aloo','jeera potato'],portionGrams:180,portionLabel:'1 bowl (~180g)',portionUnitCount:1,calories:190,protein:4,carbs:28,fat:7,fiber:5,sugar:2,sodium:300,saturatedFat:0.8,ingredients:['potato','cumin','spices','oil']},
{name:'Matar Paneer',aliases:['matar paneer','mutter paneer','peas paneer'],portionGrams:200,portionLabel:'1 bowl (~200g)',portionUnitCount:1,calories:310,protein:16,carbs:17,fat:20,fiber:5,sugar:6,sodium:470,saturatedFat:10,ingredients:['paneer','peas','tomato','onion','spices','oil']},
{name:'Kadai Paneer',aliases:['kadai paneer','karahi paneer'],portionGrams:200,portionLabel:'1 bowl (~200g)',portionUnitCount:1,calories:330,protein:17,carbs:14,fat:23,fiber:4,sugar:6,sodium:500,saturatedFat:11,ingredients:['paneer','bell pepper','tomato','onion','spices','oil']},
{name:'Dal Makhani',aliases:['dal makhani','dal makhni','maa ki dal'],portionGrams:180,portionLabel:'1 bowl (~180g)',portionUnitCount:1,calories:300,protein:12,carbs:29,fat:16,fiber:9,sugar:4,sodium:500,saturatedFat:7,ingredients:['black lentils','kidney beans','butter','cream','spices']},
{name:'Dal Palak',aliases:['dal palak','spinach dal'],portionGrams:180,portionLabel:'1 bowl (~180g)',portionUnitCount:1,calories:190,protein:10,carbs:27,fat:5,fiber:8,sugar:3,sodium:350,saturatedFat:0.8,ingredients:['lentils','spinach','tomato','spices','oil']},
{name:'Kadhi',aliases:['kadhi','kadhi pakora','punjabi kadhi'],portionGrams:220,portionLabel:'1 bowl (~220g)',portionUnitCount:1,calories:230,protein:8,carbs:24,fat:11,fiber:3,sugar:6,sodium:520,saturatedFat:4,ingredients:['yogurt','gram flour','spices','oil']},
{name:'Vegetable Biryani',aliases:['veg biryani','vegetable biryani','sabzi biryani'],portionGrams:250,portionLabel:'1 bowl (~250g)',portionUnitCount:1,calories:380,protein:9,carbs:58,fat:12,fiber:5,sugar:5,sodium:600,saturatedFat:2,ingredients:['rice','vegetables','yogurt','spices','oil']},
{name:'Chicken Biryani',aliases:['chicken biryani','murgh biryani'],portionGrams:300,portionLabel:'1 serving (~300g)',portionUnitCount:1,calories:520,protein:27,carbs:58,fat:21,fiber:3,sugar:3,sodium:850,saturatedFat:6,ingredients:['rice','chicken','yogurt','spices','oil']},
{name:'Pani Puri',aliases:['pani puri','golgappa','puchka'],portionGrams:150,portionLabel:'6 pieces (~150g)',portionUnitCount:6,calories:260,protein:6,carbs:42,fat:8,fiber:5,sugar:5,sodium:800,saturatedFat:1,ingredients:['semolina shell','potato','chickpeas','spiced water','chutney']},
{name:'Bhel Puri',aliases:['bhel puri','bhelpuri'],portionGrams:180,portionLabel:'1 plate (~180g)',portionUnitCount:1,calories:300,protein:7,carbs:50,fat:9,fiber:7,sugar:9,sodium:650,saturatedFat:1,ingredients:['puffed rice','sev','potato','onion','chutneys']},
{name:'Samosa',aliases:['samosa','aloo samosa'],portionGrams:100,portionLabel:'2 medium samosas (~100g)',portionUnitCount:2,calories:260,protein:6,carbs:32,fat:12,fiber:4,sugar:2,sodium:420,saturatedFat:2,ingredients:['potato','wheat flour','peas','spices','oil']},
{name:'Dhokla',aliases:['dhokla','khaman dhokla','khaman'],portionGrams:150,portionLabel:'3 pieces (~150g)',portionUnitCount:3,calories:210,protein:9,carbs:32,fat:5,fiber:4,sugar:4,sodium:450,saturatedFat:0.7,ingredients:['gram flour','fermented batter','spices','oil']},
{name:'Thepla',aliases:['thepla','methi thepla','methi thepla'],portionGrams:120,portionLabel:'2 medium theplas (~120g)',portionUnitCount:2,calories:280,protein:8,carbs:39,fat:10,fiber:5,sugar:2,sodium:420,saturatedFat:2,ingredients:['whole wheat flour','fenugreek','spices','oil']},
{name:'Puri',aliases:['puri','poori'],portionGrams:80,portionLabel:'2 medium puris (~80g)',portionUnitCount:2,calories:220,protein:5,carbs:30,fat:10,fiber:2,sugar:1,sodium:220,saturatedFat:2,ingredients:['wheat flour','water','oil']},
{name:'Chana Chaat',aliases:['chana chaat','chole chaat','chickpea chaat'],portionGrams:180,portionLabel:'1 bowl (~180g)',portionUnitCount:1,calories:260,protein:12,carbs:38,fat:7,fiber:10,sugar:7,sodium:500,saturatedFat:0.8,ingredients:['chickpeas','onion','tomato','chutney','spices']},
{name:'Fruit Chaat',aliases:['fruit chaat','fruit salad chaat'],portionGrams:200,portionLabel:'1 bowl (~200g)',portionUnitCount:1,calories:130,protein:2,carbs:31,fat:1,fiber:5,sugar:24,sodium:20,saturatedFat:0.1,ingredients:['mixed fruit','lemon','spices']},
{name:'Kheer',aliases:['kheer','rice kheer','payasam','payasa'],portionGrams:180,portionLabel:'1 bowl (~180g)',portionUnitCount:1,calories:250,protein:7,carbs:36,fat:9,fiber:1,sugar:24,sodium:100,saturatedFat:5,ingredients:['milk','rice','sugar','cardamom','nuts']},
{name:'Gulab Jamun',aliases:['gulab jamun','gulabjamun'],portionGrams:80,portionLabel:'2 pieces (~80g)',portionUnitCount:2,calories:260,protein:5,carbs:42,fat:9,fiber:1,sugar:30,sodium:80,saturatedFat:4,ingredients:['milk solids','flour','sugar syrup','oil']},
{name:'Jalebi',aliases:['jalebi','jilebi'],portionGrams:80,portionLabel:'3 pieces (~80g)',portionUnitCount:3,calories:300,protein:3,carbs:55,fat:9,fiber:1,sugar:38,sodium:70,saturatedFat:1.5,ingredients:['flour','sugar syrup','oil']},
{name:'Lassi',aliases:['lassi','plain lassi','dahi lassi'],portionGrams:250,portionLabel:'1 glass (~250ml)',portionUnitCount:1,calories:180,protein:7,carbs:25,fat:6,fiber:0,sugar:22,sodium:120,saturatedFat:3.5,ingredients:['yogurt','water','sugar']},
{name:'Masala Chai',aliases:['masala chai','chai','tea','tea with milk'],portionGrams:200,portionLabel:'1 cup (~200ml)',portionUnitCount:1,calories:100,protein:3,carbs:15,fat:3,fiber:0,sugar:12,sodium:50,saturatedFat:1.8,ingredients:['tea','milk','sugar','spices']}
];
