import React, { useState } from 'react';
import { useAppStore } from '../store/useAppStore';
import { Flame, Camera, Edit3, Plus, Trash2, RefreshCw, CheckCircle2, AlertTriangle, Bot } from 'lucide-react';
import { AIChatbotModal } from '../components/AIChatbotModal';

export const MealReportScreen: React.FC = () => {
  const { activeMealReport, foodCategory, setScreen, updateMealDishName, scaleMealPortion, addMealItem, removeMealItem } = useAppStore();
  const [isEditingDish,setIsEditingDish]=useState(false),[customDishInput,setCustomDishInput]=useState(''),[activePortionScale,setActivePortionScale]=useState(1),[showAddItemModal,setShowAddItemModal]=useState(false),[newItemName,setNewItemName]=useState(''),[newItemPortion,setNewItemPortion]=useState('1 Serving (~100g)'),[newItemCalories,setNewItemCalories]=useState(120),[isChatOpen,setIsChatOpen]=useState(false);
  if(!activeMealReport)return <div className="min-h-screen flex flex-col items-center justify-center p-6 bg-slate-50 text-center"><h3 className="text-base font-bold text-slate-800 mb-2">No Active Meal Report</h3><p className="text-xs text-slate-500 mb-6">Scan a homemade or restaurant meal to see item breakdown & macros.</p><button onClick={()=>setScreen('CAMERA')} className="px-5 py-2.5 bg-emerald-600 text-white text-xs font-bold rounded-xl">Open Scanner</button></div>;
  const report=activeMealReport,dishTitle=report.detectedDishName||'Scanned Meal',totals=report.totalNutrition||{calories:0,protein:0,carbs:0,fat:0,fiber:0,sugar:0,sodium:0},overallConfidence=report.confidence?.overall||0,confidenceLevel=report.confidenceLevel||(overallConfidence>=.8?'HIGH':overallConfidence>=.6?'MEDIUM':'LOW'),warnings=report.uncertaintyWarnings||[],isUncertain=confidenceLevel!=='HIGH'||warnings.length>0;
  const handleApply=(name?:string)=>{const n=name||customDishInput;if(!n.trim())return;updateMealDishName(n.trim());setIsEditingDish(false);setCustomDishInput('');};
  const handleScale=(scale:number)=>{scaleMealPortion(scale/activePortionScale);setActivePortionScale(scale);};
  const addItem=(e:React.FormEvent)=>{e.preventDefault();if(!newItemName.trim())return;addMealItem(newItemName.trim(),newItemPortion,Number(newItemCalories)||100,Math.round((newItemCalories*.08)*10)/10,Math.round((newItemCalories*.12)*10)/10,Math.round((newItemCalories*.04)*10)/10);setShowAddItemModal(false);setNewItemName('');};
  const levelClass=confidenceLevel==='HIGH'?'bg-emerald-50 text-emerald-800 border-emerald-200':confidenceLevel==='MEDIUM'?'bg-amber-50 text-amber-800 border-amber-200':'bg-rose-50 text-rose-800 border-rose-200';
  return <div className="pb-28 pt-4 px-4 space-y-4 max-w-md mx-auto">
    <div className={`p-3 rounded-2xl border ${levelClass}`}><div className="flex items-center justify-between"><span className="text-xs font-black flex items-center gap-2">{isUncertain?<AlertTriangle size={16}/>:<CheckCircle2 size={16}/>} {confidenceLevel} CONFIDENCE</span><span className="text-xs font-black">{Math.round(overallConfidence*100)}%</span></div><p className="text-[10px] mt-1 leading-snug">Meal nutrition and portions are estimates from the image. {confidenceLevel==='LOW'?'Please verify the detected items and portions before relying on the numbers.':confidenceLevel==='MEDIUM'?'Some visual or portion details are uncertain.':''}</p></div>
    {warnings.length>0&&<div className="p-3 rounded-2xl bg-amber-50 border border-amber-200"><div className="text-[10px] font-black text-amber-900 uppercase mb-1">Uncertainty notes</div><ul className="space-y-1">{warnings.slice(0,4).map((w,i)=><li key={i} className="text-[10px] text-amber-800">• {w}</li>)}</ul></div>}
    <div className="food-card p-5 rounded-3xl bg-white shadow-sm border border-slate-200"><div className="flex items-start justify-between"><div className="flex-1"><div className="flex gap-2 mb-1"><span className={`text-[10px] font-extrabold px-2 py-0.5 rounded-full border ${levelClass}`}>{Math.round(overallConfidence*100)}% Visual Confidence</span><span className="text-[10px] font-extrabold bg-slate-100 text-slate-700 border border-slate-200 px-2 py-0.5 rounded-full">{report.items?.length||0} Items</span></div><div className="flex items-center gap-2"><h2 className="text-xl font-black text-slate-900">{dishTitle}</h2><button onClick={()=>setIsEditingDish(!isEditingDish)} className="w-7 h-7 rounded-full bg-slate-100 flex items-center justify-center"><Edit3 size={14}/></button></div></div></div>{isEditingDish&&<div className="mt-3 p-3 bg-slate-50 border border-emerald-200 rounded-2xl"><div className="flex gap-2"><input value={customDishInput} onChange={e=>setCustomDishInput(e.target.value)} placeholder="e.g. Roti and Bhaji" className="bg-white border border-slate-300 rounded-xl px-3 py-2 text-xs w-full"/><button onClick={()=>handleApply()} className="bg-emerald-600 text-white px-3 rounded-xl text-xs font-black">Apply</button></div></div>}<p className="text-xs text-slate-600 leading-relaxed border-t border-slate-100 pt-3 mt-3">{report.healthSummary}</p></div>
    <div className="food-card p-4 rounded-3xl bg-white border border-slate-200 space-y-3"><div className="flex items-center justify-between"><div><h3 className="text-xs font-black text-slate-500 uppercase">Estimated Total Nutrition</h3><span className="text-[10px] text-slate-400">Image-based estimate</span></div><span className="text-sm font-black text-emerald-700 flex items-center gap-1 bg-emerald-50 px-3 py-1 rounded-full"><Flame size={16}/> ~{totals.calories} kcal</span></div><div className="bg-slate-50 p-2 rounded-2xl border border-slate-200 flex items-center justify-between"><span className="text-[10px] font-extrabold text-slate-500">PORTION</span><div className="flex gap-1">{[.5,1,1.5,2].map(s=><button key={s} onClick={()=>handleScale(s)} className={`px-2 py-1 rounded-xl text-[10px] font-black ${activePortionScale===s?'bg-emerald-600 text-white':'bg-white border'}`}>{s}x</button>)}</div></div><div className="grid grid-cols-4 gap-2 text-center">{[['Protein',totals.protein],['Carbs',totals.carbs],['Fat',totals.fat],['Fiber',totals.fiber]].map(([n,v])=><div key={String(n)} className="bg-slate-50 p-2 rounded-2xl border"><span className="text-[9px] text-slate-500 block font-black">{n}</span><span className="text-sm font-black">{v}g</span></div>)}</div></div>
    <div className="food-card p-4 rounded-3xl bg-white border border-slate-200 space-y-3"><div className="flex items-center justify-between"><h3 className="text-xs font-black text-slate-500 uppercase">Detected Meal Components ({report.items?.length||0})</h3><button onClick={()=>setShowAddItemModal(true)} className="text-[10px] font-black bg-emerald-50 text-emerald-700 border px-2.5 py-1 rounded-xl flex items-center gap-1"><Plus size={12}/> Add</button></div>{showAddItemModal&&<form onSubmit={addItem} className="p-3 bg-slate-50 border rounded-2xl space-y-2"><div className="grid grid-cols-2 gap-2"><input value={newItemName} onChange={e=>setNewItemName(e.target.value)} placeholder="Item name" className="border rounded-xl px-2 py-1.5 text-xs" required/><input type="number" value={newItemCalories} onChange={e=>setNewItemCalories(Number(e.target.value))} className="border rounded-xl px-2 py-1.5 text-xs" required/></div><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowAddItemModal(false)} className="text-xs px-3">Cancel</button><button type="submit" className="text-xs font-black bg-emerald-600 text-white px-3 py-1 rounded-xl">Add Item</button></div></form>}<div className="space-y-2">{report.items?.map((item,idx)=>{const pc=item.portionConfidence??item.confidence??0;return <div key={idx} className="bg-slate-50 p-3 rounded-2xl border space-y-2"><div className="flex justify-between gap-2"><div><h5 className="text-xs font-black">{item.name}</h5><span className="text-[10px] text-emerald-700 font-bold">Portion: {item.estimatedPortion}</span>{item.normalizedPortionGrams!=null&&<span className="block text-[9px] text-slate-500">Normalized: ~{item.normalizedPortionGrams}g</span>}</div><div className="text-right"><span className="text-xs font-black text-emerald-700 block">~{item.nutrition?.calories||0} kcal</span><span className="text-[9px] text-slate-500">Item {Math.round((item.confidence||0)*100)}% • Portion {Math.round(pc*100)}%</span><button onClick={()=>removeMealItem(idx)} className="mt-1 text-rose-600"><Trash2 size={12}/></button></div></div><div className="grid grid-cols-4 gap-1 text-center bg-white p-2 rounded-xl text-[10px] border"><span>P {item.nutrition?.protein||0}g</span><span>C {item.nutrition?.carbs||0}g</span><span>F {item.nutrition?.fat||0}g</span><span>Fib {item.nutrition?.fiber||0}g</span></div></div>})}</div></div>
    <div className="food-card p-4 rounded-3xl bg-white border border-slate-200"><h3 className="text-xs font-black text-slate-500 uppercase">Likely Ingredients</h3><div className="flex flex-wrap gap-1.5 pt-2">{report.likelyIngredients?.map((ing,i)=><span key={i} className="text-xs bg-slate-100 text-slate-700 border px-3 py-1 rounded-xl">{ing}</span>)}</div></div>
    <button onClick={()=>setIsChatOpen(true)} className="w-full py-3.5 rounded-2xl bg-teal-700 text-white font-black text-xs flex items-center justify-center gap-2"><Bot size={18}/> Ask Nutritionist AI</button><button onClick={()=>setScreen('CAMERA')} className="w-full py-4 rounded-2xl bg-emerald-600 text-white font-extrabold text-sm flex items-center justify-center gap-2"><Camera size={20}/> Scan Another Food Item</button><AIChatbotModal isOpen={isChatOpen} onClose={()=>setIsChatOpen(false)} contextFood={report}/>
  </div>;
};
