import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { emptyMealNutrition, sumMealNutrition, scaleMealNutrition, foodRating, macroEnergy, formatNutrient, contextualMealIdeas } from '../src/utils/mealNutrition';
import { MacroBreakdown, NutritionRating } from '../src/components/NutritionVisuals';
import type { MealFoodAnalysis, MealNutrition } from '../src/types';

const nutrition: MealNutrition = { calories: 400, protein: 20, carbs: 50, fat: 13, fiber: 6, sugar: 4, sodium: 300, saturatedFat: 2 };
assert.equal(formatNutrient(null), 'Unavailable');
assert.equal(formatNutrient(undefined), 'Unavailable');
assert.equal(formatNutrient(NaN), 'Unavailable');
assert.equal(formatNutrient(-1), 'Unavailable');
assert.equal(formatNutrient(0), '0 g');
assert.deepEqual(sumMealNutrition([]), emptyMealNutrition());
const partial = { ...nutrition, fiber: null };
const sum = sumMealNutrition([{ nutrition }, { nutrition: partial }]);
assert.equal(sum.calories, 800);
assert.equal(sum.fiber, null, 'Partial nutrient sums must not appear complete');
const scaled = scaleMealNutrition(partial, 1.5);
assert.equal(scaled.calories, 600);
assert.equal(scaled.fiber, null);
assert.equal(scaled.protein, 30);
assert.deepEqual(scaleMealNutrition(nutrition, NaN), nutrition);
assert.equal(foodRating(emptyMealNutrition()).score, null);
assert.equal(foodRating(partial).score, null);
assert.equal(foodRating({ ...nutrition, calories: 0 }).score, null);
assert.equal(foodRating(nutrition).score, 100);
assert.equal(foodRating(scaleMealNutrition(nutrition, 2)).score, 100, 'Density score must not change merely from doubling the portion');
assert.equal(foodRating({ ...nutrition, sodium: null, saturatedFat: null }).score, 80);
assert.equal(macroEnergy({ ...nutrition, protein: null }), null);
const shares = macroEnergy(nutrition)!;
assert.ok(Math.abs(shares.reduce((sum, item) => sum + item.share, 0) - 100) < 0.001);
const missingMarkup = renderToStaticMarkup(<><MacroBreakdown nutrition={emptyMealNutrition()} /><NutritionRating nutrition={emptyMealNutrition()} /></>);
assert.match(missingMarkup, /Unavailable/);
assert.doesNotMatch(missingMarkup, /width:/);
const knownMarkup = renderToStaticMarkup(<><MacroBreakdown nutrition={nutrition} /><NutritionRating nutrition={nutrition} estimated /></>);
assert.match(knownMarkup, /100\/100/);
assert.match(knownMarkup, /not a validated health grade/);
assert.match(knownMarkup, /exactly|Exactly/);
assert.match(knownMarkup, /20 g/);
const report = { foodClassification: 'food', detectedDishName: 'Rice', items: [{ name: 'Rice', nutrition }], totalNutrition: nutrition } as MealFoodAnalysis;
assert.ok(contextualMealIdeas(report, 'Fitness').some(idea => idea.title === 'Protein-focused option'));
assert.deepEqual(contextualMealIdeas({ ...report, items: [] }, 'Fitness'), []);
assert.deepEqual(contextualMealIdeas({ ...report, foodClassification: undefined }), []);
console.log('Meal report tests passed: unknown/zero values, complete-only totals, portion scaling, deterministic explained rating, actual macro chart, contextual suggestions.');
